version: '3'

services:
  # db:
  #   image: postgres
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: yarn serve
    volumes:
      - .:/app
    ports:
      - "8080:8080"
